---
services:
#  jackett:
#    image: ghcr.io/linuxserver/jackett
#    container_name: jackett
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=America/New_York
#      - AUTO_UPDATE=true #optional
#    volumes:
#      - /volume1/Media/Jackett/config:/config
#      - /volume1/Media/Jackett/downloads:/downloads
#    ports:
#      - 9117:9117
#    restart: unless-stopped

#  qbittorrent:
#    image: lscr.io/linuxserver/qbittorrent
#    container_name: qbittorrent
#    environment:
#      - PUID=solomonjames
#      - PGID=users
#      - TZ=America/New_York
#      - WEBUI_PORT=8585
#    volumes:
#      - /volume1/docker/home-media-server/qbittorrent-config:/config
#      - /volume1/Media:/volume1/Media
#    ports:
#      - 6881:6881
#      - 6881:6881/udp
#      - 8585:8585
#    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=solomonjames
      - PGID=users
      - TZ=America/New_York
    volumes:
      - /volume1/Media:/volume1/Media
      - /volume1/docker/home-media-server/.config/sabnzbd:/config
      - /volume1/Media/Downloads:/downloads
      - /volume1/Media/Downloads/Incomplete:/incomplete-downloads
    ports:
      - 8080:8080
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=solomonjames
      - PGID=users
      - TZ=America/New_York
    volumes:
      - /volume1/Media:/volume1/Media
      - /volume1/docker/home-media-server/.config/radarr:/config
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=solomonjames
      - PGID=users
      - TZ=America/New_York
    volumes:
      - /volume1/Media:/volume1/Media
      - /volume1/docker/home-media-server/.config/sonarr:/config
    ports:
      - 8989:8989
    restart: unless-stopped
